openapi: 3.0.3
info:
  title: API Biblioteca UPEL - Libros
  version: 1.0.0
  description: Documentación de la API de gestión de libros de la biblioteca UPEL
servers:
  - url: http://localhost:5000/api
paths:
  /book:
    get:
      summary: Obtener todos los libros
      tags: [Books]
      security:
        - bearerAuth: []
      responses:
        200:
          description: Lista de libros
    post:
      summary: Crear un nuevo libro
      tags: [Books]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookInput'
            example:
              title: "Cien años de soledad"
              author: "Gabriel García Márquez"
              isbn: "978-0307474728"
              publisher: "Editorial Sudamericana"
              publication_year: 1967
              edition: "Primera"
              language: "Español"
              description: "Novela emblemática de la literatura latinoamericana."
              academic_program_id: 1
      responses:
        201:
          description: Libro creado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookInput'
              example:
                title: "Cien años de soledad"
                author: "Gabriel García Márquez"
                isbn: "978-0307474728"
                publisher: "Editorial Sudamericana"
                publication_year: 1967
                edition: "Primera"
                language: "Español"
                description: "Novela emblemática de la literatura latinoamericana."
                academic_program_id: 1
        400:
          description: Error de validación
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                message: "Datos inválidos"
                field: "isbn"
                code: "VALIDATION_ERROR"
  /book/{id}:
    get:
      summary: Obtener un libro por ID
      tags: [Books]
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Libro encontrado
        404:
          description: Libro no encontrado
    put:
      summary: Actualizar un libro
      tags: [Books]
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookInput'
      responses:
        200:
          description: Libro actualizado
        400:
          description: Error de validación
        404:
          description: Libro no encontrado
    delete:
      summary: Eliminar un libro
      tags: [Books]
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Libro eliminado
        404:
          description: Libro no encontrado
components:
  schemas:
    BookInput:
      type: object
      required:
        - title
        - author
        - isbn
        - publisher
        - publication_year
      properties:
        title:
          type: string
          description: Título del libro
          example: "Cien años de soledad"
        author:
          type: string
          description: Autor del libro
          example: "Gabriel García Márquez"
        isbn:
          type: string
          description: ISBN del libro
          example: "978-0307474728"
        publisher:
          type: string
          description: Editorial
          example: "Editorial Sudamericana"
        publication_year:
          type: integer
          description: Año de publicación
          example: 1967
        edition:
          type: string
          description: Edición del libro
          example: "Primera"
        language:
          type: string
          description: Idioma
          example: "Español"
        description:
          type: string
          description: Descripción del libro
          example: "Novela emblemática de la literatura latinoamericana."
        academic_program_id:
          type: integer
          description: ID del programa académico relacionado
          example: 1
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          description: Mensaje de error
        field:
          type: string
          description: Campo que causó el error (si aplica)
        code:
          type: string
          description: Código de error
security:
  - bearerAuth: []
