openapi: 3.0.3
info:
  title: API Biblioteca UPEL - Libros
  version: 1.0.0
  description: Documentación de la API de gestión de libros de la biblioteca UPEL
servers:
  - url: http://localhost:5000/api
paths:
  /book:
    get:
      summary: Obtener todos los libros (paginado opcional)
      tags: [Books]
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: page
          schema:
            type: integer
          description: Número de página (opcional)
          example: 1
        - in: query
          name: limit
          schema:
            type: integer
          description: Cantidad de libros por página (opcional)
          example: 10
      responses:
        200:
          description: Lista de libros (paginada si se usan page y limit)
          content:
            application/json:
              schema:
                oneOf:
                  - type: array
                    items:
                      $ref: '#/components/schemas/BookInput'
                  - type: object
                    properties:
                      books:
                        type: array
                        items:
                          $ref: '#/components/schemas/BookInput'
                      pagination:
                        type: object
                        properties:
                          total:
                            type: integer
                            example: 100
                          page:
                            type: integer
                            example: 1
                          pages:
                            type: integer
                            example: 10
                          limit:
                            type: integer
                            example: 10
              examples:
                paginada:
                  summary: Respuesta paginada
                  value:
                    books:
                      - title: "Cien años de soledad"
                        author: "Gabriel García Márquez"
                        isbn: "978-0307474728"
                        publisher: "Editorial Sudamericana"
                        publication_year: 1967
                        edition: "Primera"
                        language: "Español"
                        description: "Novela emblemática de la literatura latinoamericana."
                        academic_program_id: 1
                    pagination:
                      total: 100
                      page: 1
                      pages: 10
                      limit: 10
                sin_paginacion:
                  summary: Respuesta sin paginación
                  value:
                    - title: "Cien años de soledad"
                      author: "Gabriel García Márquez"
                      isbn: "978-0307474728"
                      publisher: "Editorial Sudamericana"
                      publication_year: 1967
                      edition: "Primera"
                      language: "Español"
                      description: "Novela emblemática de la literatura latinoamericana."
                      academic_program_id: 1
    post:
      summary: Crear un nuevo libro
      tags: [Books]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookInput'
            example:
                title: "Cien años de soledad"
                author: "Gabriel García Márquez"
                isbn: "978-0307474728"
                publisher: "Editorial Sudamericana"
                publication_year: 1967
                edition: "Primera"
                category: "Física"
                description: "Novela emblemática de la literatura latinoamericana."
      responses:
        201:
          description: Libro creado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookInput'
              example:
                title: "Cien años de soledad"
                author: "Gabriel García Márquez"
                isbn: "978-0307474728"
                publisher: "Editorial Sudamericana"
                publication_year: 1967
                edition: "Primera"
                category: "Física"
                description: "Novela emblemática de la literatura latinoamericana."
        400:
          description: Error de validación
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                message: "Datos inválidos"
                field: "isbn"
                code: "VALIDATION_ERROR"
        403:
          description: Acceso denegado
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Acceso denegado solo administradores.
  /book/{isbn}:
    get:
      summary: Buscar libro por ISBN
      tags: [Books]
      security:
        - bearerAuth: []
      parameters:
        - name: isbn
          in: path
          required: true
          schema:
            type: string
          description: ISBN del libro a buscar
      responses:
        200:
          description: Libro encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookInput'
              example:
                title: "Cien años de soledad"
                author: "Gabriel García Márquez"
                isbn: "978-0307474728"
                publisher: "Editorial Sudamericana"
                publication_year: 1967
                edition: "Primera"
                language: "Español"
                description: "Novela emblemática de la literatura latinoamericana."
                academic_program_id: 1
        404:
          description: Libro no encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                message: "Libro no encontrado"
  /book/{title}:
    get:
      summary: Buscar libro por título
      tags: [Books]
      security:
        - bearerAuth: []
      parameters:
        - name: title
          in: path
          required: true
          schema:
            type: string
          description: Título del libro a buscar
      responses:
        200:
          description: Libro encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookInput'
              example:
                title: "Cien años de soledad"
                author: "Gabriel García Márquez"
                isbn: "978-0307474728"
                publisher: "Editorial Sudamericana"
                publication_year: 1967
                edition: "Primera"
                language: "Español"
                description: "Novela emblemática de la literatura latinoamericana."
                academic_program_id: 1
        404:
          description: Libro no encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                message: "Libro no encontrado"
  /book/{id}:
    put:
      summary: Actualizar un libro (permite actualización parcial o completa)
      tags: [Books]
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: Título del libro
                author:
                  type: string
                  description: Autor del libro
                publisher:
                  type: string
                  description: Editorial
                publication_year:
                  type: integer
                  description: Año de publicación
                category:
                  type: string
                  description: Categoría
                edition:
                  type: string
                  description: Edición
                description:
                  type: string
                  description: Descripción del libro
                is_available:
                  type: boolean
                  description: Disponibilidad
                cover_url:
                  type: string
                  description: URL de la portada
            examples:
              actualizacion_parcial:
                summary: Solo se actualiza el título y la disponibilidad
                value:
                  title: "Nuevo título"
                  is_available: false
              actualizacion_completa:
                summary: Todos los campos actualizados
                value:
                  title: "Programación Avanzada"
                  author: "Juan Pérez"
                  publisher: "Editorial UPEL"
                  publication_year: 2024
                  category: "Informática"
                  edition: "Tercera"
                  description: "Libro actualizado con todos los datos."
                  is_available: true
                  cover_url: "https://biblioteca.upel.edu.ve/covers/programacion-avanzada.jpg"
      responses:
        200:
          description: Libro actualizado
        400:
          description: Error de validación o campos no válidos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                message: "Campos no válidos: foo, bar"
        404:
          description: Libro no encontrado
        403:
          description: Acceso denegado
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Acceso denegado solo administradores.
    delete:
      summary: Eliminar un libro
      tags: [Books]
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Libro eliminado
        404:
          description: Libro no encontrado
        403:
          description: Acceso denegado
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Acceso denegado solo administradores.
components:
  schemas:
    BookInput:
      type: object
      required:
        - title
        - author
        - isbn
        - publisher
        - publication_year
      properties:
        title:
          type: string
          description: Título del libro
          example: "Cien años de soledad"
        author:
          type: string
          description: Autor del libro
          example: "Gabriel García Márquez"
        isbn:
          type: string
          description: ISBN del libro
          example: "978-0307474728"
        publisher:
          type: string
          description: Editorial
          example: "Editorial Sudamericana"
        publication_year:
          type: integer
          description: Año de publicación
          example: 1967
        edition:
          type: string
          description: Edición del libro
          example: "Primera"
        language:
          type: string
          description: Idioma
          example: "Español"
        description:
          type: string
          description: Descripción del libro
          example: "Novela emblemática de la literatura latinoamericana."
        academic_program_id:
          type: integer
          description: ID del programa académico relacionado
          example: 1
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          description: Mensaje de error
        field:
          type: string
          description: Campo que causó el error (si aplica)
        code:
          type: string
          description: Código de error
security:
  - bearerAuth: []
